name: 下载
on:
  workflow_dispatch:
    inputs:
      url:
        description: '影片地址'
        type: string
        required: true
jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: 设置 Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.8'
      - name: 安装 yt-dlp
        run: python3 -m pip install -U "yt-dlp[default]"
      - name: 创建文件夹
        run: mkdir video
      - name: 下载
        run: cd video $$ yt-dlp ${{ inputs.url }} --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
        #run: cd video && yt-dlp URL ${{ inputs.url }} --extractor-args "youtube:po_token=web.gvs+${{secrets.PO_TOKEN}}"
      - name: 打包
        uses: actions/upload-artifact@v4.5.0
        with:
          path: video
